package com.regisx001.validationsystem.domain.enums;

public enum AnalyseAction {
    SUBMITTED,
    AI_ANALYSIS_STARTED,
    AI_ANALYSIS_COMPLETED,
    AUTO_APPROVED,
    AUTO_REJECTED,
    MANUAL_REVIEW_REQUESTED,
    MANUALLY_APPROVED,
    MANUALLY_REJECTED,
    REVISION_REQUESTED,
    RESUBMITTED,
    PUBLISHED,
    ARCHIVED
}
